// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#define CHARACTER_DEFAULT_SCALE					45.0

#define PROBE_SIZE								5.f

#define LOBBY_CHARACTER_ANIM_BIT_IDLE			0x00000001
#define LOBBY_CHARACTER_ANIM_BIT_PICKED			0x00000002
#define LOBBY_CHARACTER_ANIM_BIT_PICKEDIDLE		0x00000004
#define LOBBY_CHARACTER_ANIM_BIT_UNPICKED		0x00000008


#define GP_ANIM_BIT_IDLE						0x00000001
#define GP_ANIM_BIT_WALK						0x00000002
#define GP_ANIM_BIT_RUN							0x00000004

#define CHARACTER_CAPSULE_HALF_HEIGHT			45.f



#define CHARACTER_TARGETARMLENGTH				300.f

#define COLLISION_HIDDEN_IN_GAME				false

#define MARIOATTACK_LENGTH						50.f
#define YOSHI_EGG_HOLD_OFFSET					80.f

#define AISENSECONFIG_SIGHT_SIGHTRADIUS										1000.f
#define AISENSECONFIG_SIGHT_LOSESIGHTRADIUS									600.f
#define AISENSECONFIG_SIGHT_LOSESIGHTRADIUS_PERIPHERALVISIONANGLEDEGREES	120.f


#define EGG_MAX_COOLTIME						10.f

#define EGG_SCALE								60.0
#define EGG_BOX_EXTENT							0.25

#define MARIO_WALK_SPEED						200.f
#define MARIO_RUN_SPEED							420.f
#define YOSHI_WALK_SPEED						200.f
#define YOSHI_RUN_SPEED							400.f

#define YOSHI_MAX_STAMINA						150.f
#define MARIO_MAX_STAMINA						100.f

#define YOSHI_STAMINA_REGEN						15
#define MARIO_STAMINA_REGEN						20
#define YOSHI_STAMINA_CONSUME					30	
#define MARIO_STAMINA_CONSUME					40

#define YOSHI_MAX_HP							100.f
#define MARIO_MAX_HP							100.f
#define MARIO_ATTACK_DAMAGE						5.f

#define EXHAUSTE_TIME							3.f

#define EGG_GAUGE_COEFFICIENT					0.01f

#define GAME_TIME_LIMIT							500